name: Sports Facility Checker

on:
  schedule:
    # Run every hour from 9AM to 11PM JST (0AM to 2PM UTC, JST is UTC+9)
    - cron: '0 0-14 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  check-facilities:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Get Playwright version
      id: playwright-version
      run: echo "version=$(python -c "import playwright; print(playwright.__version__)")" >> $GITHUB_OUTPUT
        
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-playwright-
        
    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: playwright install chromium
      
    - name: Install Playwright system dependencies
      run: playwright install-deps
        
    - name: Run sports facility checker
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python main.py 